#!/bin/bash -xe

sudo su - jenkins -c "echo '
OPENSTACK_HOST=${OPENSTACK_HOST}
APT_PROXY_HOST=${APT_PROXY_HOST}
RABBITMQ_MGMT_PORT=15672
RABBITMQ_URL=${OPENSTACK_HOST}
RABBITMQ_HOST=${OPENSTACK_HOST}
RABBITMQ_PORT=5672
ADMIN_USERNAME=${OPENSTACK_ADMIN_USER}
ADMIN_PASSWORD=${OPENSTACK_ADMIN_PASS}
ADMIN_TENANT=${OPENSTACK_ADMIN_TENANT}
KEYSTONE_URL=${OPENSTACK_HOST}
LINUX_IMAGE=cloud-fedora-v3
' > /home/jenkins/credentials"

if [ -n "${JENKINS_PUBLIC_KEY}" ]; then
    sudo su - jenkins -c "echo '${JENKINS_PUBLIC_KEY}' >> /home/jenkins/.ssh/authorized_keys"
fi
